[package]
name = "glanguage"
version = "0.1.0-alpha"
authors = ["Jos√© Carlos <josecarlosskar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
